### PR TITLE
Add support for fullscreen option

### PR DESCRIPTION
**Pull request by terlar**
If someone want to open the application in fullscreen without
menu-bar (windows/linux). This will put the application in fullscreen
mode.

Another option could also be to only hide the menu without setting
fullscreen. But this works for me.

That would use something like:

```
win.setMenu(null);
```

Fix for #1

### CODE REVIEW

**Comment by rhysd** [comment]
Looks good. Thank you.

**Comment by rhysd** [comment]
I published v1.4.1

**Comment by terlar** [comment]
Thank you for the quick response :bowing_man:

**Comment by rhysd** [comment]
It's fine. Thank you for contribution :+1:

**Pull request merged**
